"""First migration

Revision ID: 17e06a0b66a6
Revises: 30372463daae
Create Date: 2023-06-21 15:03:42.060017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e06a0b66a6'
down_revision = '30372463daae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fully_invested', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('invested_amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('invested_amount')
        batch_op.drop_column('fully_invested')

    # ### end Alembic commands ###
